FROM python:3.9-slim
WORKDIR /app
RUN addgroup --system python && \
    adduser --system --disabled-password --ingroup python python && chown python:python /app
USER python
RUN python -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"
COPY --chown=python:python requirements.txt ./
RUN --mount=type=cache,target=~/.cache/pip pip install -r requirements.txt
COPY --chown=python:python . .
CMD ["python", "main.py"]
